dl_data_lake:
  yfinance:
    prices:
      # 날짜 범위 (period vs start/end 중 하나만 사용)
      start: "2023-01-01"     # YYYY-MM-DD
      end: null               # null이면 오늘까지

#      # 캔들 설정
#      interval: "1d"          # 1m,5m,15m,1h,1d,1wk,1mo
#
#      # 옵션
#      auto_adjust: true
#      actions: false          # dividends / splits
#      prepost: false          # 장외거래